config/routes.rb
Rails.application.routes.draw do
  resources :datos
  devise_for :users
  devise_for :models
  
  

  
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "/index" => 'home#index'
  get "/admin" => 'admin/dashboard#index'
  get "sitio"  => 'home#sitio', as: 'sitio'
    get "carta"  => 'home#carta', as: 'carta'
 
   root 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/dato.rb
class Dato < ActiveRecord::Base
    
    belongs_to :user 
end

app/models/menu.rb
class Menu < ActiveRecord::Base
    
    belongs_to :restaurante
    

     validates :entrada, presence: true
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/restaurante.rb
class Restaurante < ActiveRecord::Base
    
    has_many :menus
    validates :nombre, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         has_many :datos 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/datos_controller.rb
class DatosController < ApplicationController
  before_action :set_dato, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /datos
  # GET /datos.json
  def index
    @datos = Dato.all
  end

  # GET /datos/1
  # GET /datos/1.json
  def show
  end

  # GET /datos/new
  def new
    @dato = current_user.datos.build
  end

  # GET /datos/1/edit
  def edit
  end

  # POST /datos
  # POST /datos.json
  def create
    @dato = current_user.datos.build(dato_params)

    respond_to do |format|
      if @dato.save
        format.html { redirect_to @dato, notice: 'Dato was successfully created.' }
        format.json { render :show, status: :created, location: @dato }
      else
        format.html { render :new }
        format.json { render json: @dato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /datos/1
  # PATCH/PUT /datos/1.json
  def update
    respond_to do |format|
      if @dato.update(dato_params)
        format.html { redirect_to @dato, notice: 'Dato was successfully updated.' }
        format.json { render :show, status: :ok, location: @dato }
      else
        format.html { render :edit }
        format.json { render json: @dato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datos/1
  # DELETE /datos/1.json
  def destroy
    @dato.destroy
    respond_to do |format|
      format.html { redirect_to datos_url, notice: 'Dato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dato
      @dato = Dato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dato_params
      params.require(:dato).permit(:fullname, :phone, :direccion)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
    
    def sitio
       @restaurantes = Restaurante.all 
    end
    
    
    def carta
       @menus = Menu.all 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datos_helper.rb
module DatosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/datos/_form.html.erb
<%= form_for(@dato) do |f| %>
  <% if @dato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dato.errors.count, "error") %> prohibited this dato from being saved:</h2>

      <ul>
      <% @dato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fullname %><br>
    <%= f.text_field :fullname %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/datos/edit.html.erb
<h1>Editing Dato</h1>

<%= render 'form' %>

<%= link_to 'Show', @dato %> |
<%= link_to 'Back', datos_path %>

app/views/datos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Datos</h1>


 
 

                  

<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Phone</th>
      <th>Direccion</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @datos.each do |dato| %>
    <% if dato.user == current_user  %>
      <tr>
        <td><%= dato.fullname %></td>
        <td><%= dato.phone %></td>
        <td><%= dato.direccion %></td>
        <td><%= dato.user.email %></td>
        <td><%= link_to 'Show', dato %></td>
        <td><%= link_to 'Edit', edit_dato_path(dato) %></td>
        <td><%= link_to 'Destroy', dato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
         <% end  %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dato', new_dato_path %>

app/views/datos/new.html.erb
<h1>New Dato</h1>

<%= render 'form' %>

<%= link_to 'Back', datos_path %>

app/views/datos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @dato.fullname %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @dato.phone %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @dato.direccion %>
</p>

<%= link_to 'Edit', edit_dato_path(@dato) %> |
<%= link_to 'Back', datos_path %>

app/views/home/carta.html.erb
<%= stylesheet_link_tag 'restaurante', media: 'all', 'data-turbolinks-track' => true %>
<h1><a>La Carta
	

<% @menus.each do |menu| %>


   <%= menu.restaurante.nombre %>
       
         <% end  %>
           </a> </h1>
         <table>
  <thead>
    <tr>
      <th>Plato de Entrada</th>
      <th>Plato de Fondo</th>
      <th>Postre</th>
      <th>Bebida</th>
      <th>Precio</th>
  
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>

      <tr>
        <td><%= menu.entrada %></td>
         <td><%= menu.plato_fondo%></td>
         <td><%= menu.postre%></td>
          <td><%= menu.bebida %></td>
           <td><%= menu.precio %></td>
      </tr>
  
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
 <% if model_signed_in?  %>
 
 
<%= link_to "Cerra Sesión", destroy_user_session_path, method: :delete %>
                     <% end  %>XD

app/views/home/probando.html.erb
DX

app/views/home/restaurant.html.erb
<%= stylesheet_link_tag 'restaurante', media: 'all', 'data-turbolinks-track' => true %>
       
                             


  <%= csrf_meta_tags %>
  

	<h1><a>RESTAURANTES</a> </h1>

app/views/home/sitio.html.erb
<%= stylesheet_link_tag 'restaurante', media: 'all', 'data-turbolinks-track' => true %>
       
                             


  <%= csrf_meta_tags %>
  

	<h1><a>Restaurante
	
	
	<% @restaurantes.each do |restaurante| %>


   <%= restaurante.nombre %>
       
         <% end  %>
         
         </a> </h1>
         
         <% @restaurantes.each do |restaurante| %>


   <%= restaurante.descripcion %>
       
         <% end  %>
         
         
          <% @restaurantes.each do |restaurante| %>
          </br>

<ul>
   <li>"DIRECCIÓN" <%= restaurante.telefono %></li>
   <br>
    <li>"TÉLEFONO" <%= restaurante.direccion %></li>
       </ul>
         <% end  %>
         
         
         
         <nav class="menu nav_wrapper" id="myslidemenu">

    <ul class="menu" id="jqueryslidemenu">
    <li class="current"><a href="carta"><i class="fa fa-cutlery"></i>La Carta</a></li>
		
	
	</ul>
</nav>

         
         
         

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
<title>Cooks HTML Template</title>

  

     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
                             
  

  <%= csrf_meta_tags %>
  





</head>
<body>
  
  <!--Control Bar Start-->
<div id="controls-wrapper" class="load-item">
<div id="controls">			
    <ul id="slide-list"></ul>			
</div>
</div>
<!--Control Bar End-->

<!--Logo Start-->

	<h1>Perú Pedido</h1>
    <h4>Más de 50 restaurantes con delivery en Lima</h4>

<!--Logo End-->

<!--Menu Start-->
<nav class="menu nav_wrapper" id="myslidemenu">
    <ul class="menu" id="jqueryslidemenu">
        <li class="current"><a href="/index"><i class="fa fa-home"></i>Inicio</a></li>
          <li><a href="/sitio"><i class="fa fa-cutlery"></i>Restaurantes</a>
          
          <% if user_signed_in?  %>
 
  <li><%= link_to "Perfil", datos_path %></li>
  <li><%= link_to "Pedidos", new_user_registration_path%></li>
   <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></li>
  <% else %>
  
  	<li><%= link_to "Registrate", new_user_registration_path%></li>
	 <li><%= link_to "Iniciar Sesión", new_user_session_path %></li>
                     <% end  %>
		
               <li><a href="contact.html"><i class="fa fa-comments"></i>Contáctenos</a></li>
   
             
               
        

	
		 
		
    </ul>
</nav>

<!--Menu End-->


<!--Intro Text Start-->



  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>